---
- name: Prerequisites
  include_tasks: check-kubectl-installed.yml

- name: Certificates generation
  include_tasks: generate-certs.yml

- name: Certificates coping
  include_tasks: copy-certs.yml

- name: Kubeconfig generation
  include_tasks: generate-kubeconfig.yml

- name: Context setting
  include_tasks: set-kubectl-context.yml
