---
- block:  # Install Kubernetes packages

   - name: Installing Kubernetes packages.
     apt: 
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present

    when:
      - ansible_os_family == 'Debian'
      - kubernetes_installed is false
