---
- block:  # Add Kubernetes APT repository

  - name: Ensure /etc/apt/keyrings exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Kubernetes signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add additional public key
    apt_key:
      id: 234654DA9A296436
      keyserver: keyserver.ubuntu.com
      state: present

  - name: Add Kubernetes apt repository
    apt_repository:
      repo: 'deb https://packages.cloud.google.com/apt/ kubernetes-xenial main'
      state: present
      filename: kubernetes.list
      update_cache: yes

  when:
    - ansible_os_family == 'Debian'
