---
- block:  # Add Kubernetes APT repository

  - name: Ensure /etc/apt/keyrings exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Kubernetes signing key
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      mode: '0644'

  - name: Add Kubernetes apt repository
    lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
      create: yes
      state: present

  - name: Update APT cache
    apt:
      update_cache: yes

  when:
    - ansible_os_family == 'Debian'
