---
- block:  # Configure Linux kernel parameters for Kubernetes

   - name: Create a empty file for kubernetes sysctl params.
     copy:
        content: ""
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        force: no

   - name: Configure sysctl params for Kubernetes.
     lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf 
        line: "{{ item }}"
     with_items:
       - 'net.bridge.bridge-nf-call-iptables  = 1'
       - 'net.ipv4.ip_forward                 = 1'
       - 'net.bridge.bridge-nf-call-ip6tables = 1'

   - name: Apply sysctl params
      command: sysctl --system
