---
- block:  # Add Docker APT repository

  - name: Create a directory for repository keys
    file:
      path: /usr/share/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker GPG key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /usr/share/keyrings/docker-archive-keyring.gpg
      mode: '0644'

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  when:
    - ansible_os_family == 'Debian'
