---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.1\.1)\s+'
    line: "127.0.1.1\t{{ inventory_hostname }}"
